".config/bat/syntaxes":
  type: archive
  url: "https://github.com/odin-lang/sublime-odin/archive/refs/heads/master.zip"
  stripComponents: 1
  include: ["**/*.sublime-syntax"]

{{- $fontDir := "" }}
{{- if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{- else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{- end }}
"{{ $fontDir }}/Fira_Code":
  type: archive
  url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip"
  include: ["**/*.ttf"]
"{{ $fontDir }}/Meslo_LG":
  type: archive
  url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.zip"
  include: ["**/*.ttf"]
