- 1.1.10
- _NAME: Craft Advanced Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, divert-gkeys, m-key-leds,
    mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B35040660000
  _sensitive: {backlight: false, change-host: false, fn-swap: false, multiplatform: false, persistent-remappable-keys: true}
  _unitId: 5F0BE964
  backlight: true
  change-host: null
  crown-smooth: false
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-crown: false
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0,
    234: 0, 235: 0, 236: 0, 255: 0}
  fn-swap: true
  multiplatform: 1
  persistent-remappable-keys: null
- _NAME: Wireless Mouse MX Master 2S
  _absent: [hi-res-scroll, lowres-scroll-mode, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight,
    backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform,
    gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B01940690000
  _sensitive: {hires-smooth-invert: false}
  _unitId: 1155BA61
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1000
  gesture2-divert: {46: false}
  gesture2-gestures: {45: true, 46: true}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 1
  smart-shift: 1
