[colors]
foreground = '#c6b8ad'
background = '#161c23'
cursor_fg = '#161c23'
cursor_bg = '#abb2bf'
cursor_border = '#abb2bf'
selection_bg = '#313f4e'
scrollbar_thumb = '#c6b8ad'

[metadata]
aliases = []
author = 'RichardFevrier'
name = 'Bogster'
origin_url = 'https://github.com/RichardFevrier/wezterm-bogster'
