[mgr]
sort_dir_first = false
show_hidden = true
linemode = "mtime"
sort_by = "natural"

# [opener]
# delta = [
# 	{ run = 'delta "$1" "$2"', desc = "Delta", for = "unix"  },
# ]
#
# [open]
# prepend_rules = [
# 	{ mime = "text/*", use = "delta" },
# ]
