format = "$all$line_break$shlvl$shell$character"
add_newline = false

[character]
error_symbol = "[\\$](bold #fb467b)"
success_symbol = "[\\$](bold #56d6d6)"

[cmd_duration]
style = "bold #C3E88D"

[directory]
style = "bold #C3E88D"
truncation_length = 2
truncate_to_repo = false

[git_branch]
style = "bold #CB6CFE"

[git_status]
style = "bold #fb467b"

[hostname]
style = "bold #56D6D6"

[shell]
disabled = false

[shlvl]
disabled = false
format = '$symbol '
symbol = '❯'
repeat = true

[sudo]
disabled = false

[username]
format = "[$user]($style) on "
style_user = "bold #6796E6"
